TestName,Result,Message
test_Assertion_SE_cwe252_0,Compilation error,"'{' was never closed (Assertion_SE_cwe252_0.py, line 31)"
