TestName,Result,Message
test_Assertion_SS_cwe099_0.TestCWE099_0.test_correctness,error,[Errno 2] No such file or directory: './static/dummy.py'
test_Assertion_SS_cwe099_0.TestCWE099_0.test_vulnerability,success,
